config/routes.rb
Rails.application.routes.draw do
  resources :users 
  resources :recipe
  resources :ingredients

  root 'users#index'
  get '/signup', to: 'users#signup'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'users#destroy'
  get '/lowcal', to: 'ingredients#lowcal'
  

  get '/auth/google_oauth2/callback', to: 'sessions#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# match '/app/github/callback', to: 'sessions#create', via: [:get, :post]
# root 'welcome#home'

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipes
    has_many :users, through: :recipes

    validates :name, length: { maximum: 15 }

    scope :low_cal_ingredients, -> { self.where("calories < '50'") }

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    
    def index
        @ingredients = Ingredient.all
        @recipes = current_user.recipes
        @user = current_user
    end 

    def new 
        @ingredients = Ingredient.new
        @recipe = Recipe.all.select{|m| m.user_id == current_user.id}
    end 

    def create 
        @ingredients = Ingredient.new(ingredient_params)
        if !params[:ingredient][:recipes].empty?
            @ingredients.recipes << Recipe.find_by(name: params[:ingredient][:recipes])
        end 
        if @ingredients.valid?
            @ingredients.save!
            redirect_to ingredient_path(@ingredients)
        else 
            @recipe = Recipe.all.select{|m| m.user_id == current_user.id}
            render :new
        end 
    end
    
    def show
        @ingredient = Ingredient.find_by(id: params[:id])
    end

    def edit
        @ingredient = Ingredient.find_by(id: params[:id])
        @user = current_user
        if !logged_in?
            redirect_to '/login'
        else 
            if @ingredient.user_ids.include?(current_user.id)
                render :edit
            else
                redirect_to ingredient_path(@user)
            end 
        end 
    end 

    def update
        @ingredient = Ingredient.find_by(id: params[:id])
        @ingredient.update(ingredient_params)
        redirect_to ingredient_path(@ingredient)
    end 

    def destroy
        if current_user
            Ingredient.find_by(id: params[:id]).destroy
            redirect_to ingredients_path
        end 
    end

    def lowcal
        @user = current_user.id
        @low_cal = Ingredient.low_cal_ingredients
        render :low_cal
    end 
    
    private

    def ingredient_params
        params.require(:ingredient).permit(:name, :calories, :fats, :protein, :carbohydrates)
    end

end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/edit.html.erb
<h1>Welcome to Ingredients Edit Form</h1>

<%= form_for @ingredient do |f| %>
  
  <%= f.label 'Name of Ingredient' %>
  <%= f.text_field :name %></br>
  </br>
  <%= f.label 'Calories' %>
  <%= f.number_field :calories %></br>
  </br>
  <%= f.label 'Fats' %>
  <%= f.number_field :fats %></br>
  </br>
  <%= f.label 'Carbohydrates' %>
  <%= f.number_field :carbohydrates %></br>
  </br>
  <%= f.label 'Protein' %>
  <%= f.number_field :protein %></br>
  </br>
  <%= f.submit 'Update Ingredient' %>

<% end %>
</br>
<button><%= link_to 'Delete this Ingredient', ingredient_path(@ingredient), method: :delete %></button>

 

app/views/ingredients/index.html.erb
<h1>Welcome to the Ingredient Index</h1>

<h1>All Ingredients</h1>

<% @ingredients.each do |ingredient| %>
    <%= link_to ingredient.name, edit_ingredient_path(ingredient) %></br>
    </br>
<% end %>

<button><%= link_to 'Create an Ingredient', new_ingredient_path %></button></br>
</br>
<button><%= link_to 'See all Low Cal Ingredients', '/lowcal' %></button></br>
</br>
<button><%= link_to 'Head back to Recipes', recipe_index_path(@user) %></button></br>

app/views/ingredients/low_cal.html.erb
<% @low_cal.each do |x| %>
    <h3>Ingredient Name: <%= x.name %></h3>
    <h5>Calories: <%= x.calories %></h5>
    <h5>Fats: <%= x.fats %></h5>
    <h5>carbohydrates: <%= x.carbohydrates %></h5>
    <h5>Protein: <%= x.protein %></h5>
<% end %>

<button><%= link_to 'Head back to Recipes', recipe_index_path(@user) %></button></br>
</br>
<button><%= link_to 'Back to Ingredients Index', ingredients_path %></button></br>

app/views/ingredients/new.html.erb
<h1>Welcome to the New Ingredients Form</h1>
<%= form_for @ingredients do |f| %>
  <% if @ingredients.errors.any? %>
    <div id="error_explanation">
        <h2>There were some errors:</h2>
        <ul>
            <% @ingredients.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
  <% end %>
  <div class="field<%= ' field_with_errors' if @ingredients.errors[:name].any? %>">
  <%= f.label 'Name of Ingredient' %>
  <%= f.text_field :name %></br>
  </div>
  </br>
  <%= f.label 'Calories' %>
  <%= f.number_field :calories %></br>
  </br>
  <%= f.label 'Fats' %>
  <%= f.number_field :fats %></br>
  </br>
  <%= f.label 'Carbohydrates' %>
  <%= f.number_field :carbohydrates %></br>
  </br>
  <%= f.label 'Protein' %>
  <%= f.number_field :protein %></br>
  </br>
  <i>Select one of your recipe's to add this ingredient to it</i></br>
  <%= f.collection_select :recipes, @recipe, :name, :name, {include_blank: 'Select a Recipe'} %></br>
  </br>
  <%= f.submit 'Add Ingredient To Recipe' %>

<% end %>

 

app/views/ingredients/show.html.erb
<h1>Welcome to the Ingredients Show</h1>

<h3>Ingredient Name: <%= @ingredient.name %></h3>
<h5>Calories: <%= @ingredient.calories %></h5>
<h5>Fats: <%= @ingredient.fats %></h5>
<h5>carbohydrates: <%= @ingredient.carbohydrates %></h5>
<h5>Protein: <%= @ingredient.protein %></h5>

<button><%= link_to 'Back to Ingredients Index', ingredients_path %></button></br>
</br>
<button><%= link_to 'Delete this Ingredient', ingredient_path(@ingredient), method: :delete %></button>