config/routes.rb
Rails.application.routes.draw do
  resources :users 
  resources :recipe
  resources :ingredients

  root 'users#index'
  get '/signup', to: 'users#signup'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'users#destroy'
  get '/lowcal', to: 'ingredients#lowcal'
  

  get '/auth/google_oauth2/callback', to: 'sessions#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# match '/app/github/callback', to: 'sessions#create', via: [:get, :post]
# root 'welcome#home'

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    belongs_to :ingredient
    

end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController

    def index
        if session[:user_id]
            @user = User.find_by(id: session[:user_id])
            @recipes = Recipe.all
            binding.pry
        elsif params[:format]
            session[:user_id] = params[:format]
            @user = User.find_by(id: params[:format])
            @recipes = Recipe.all
            binding.pry
        else 
            binding.pry
            redirect_to '/'
        end 
    end 

    def new 
        @recipe = Recipe.new
        @user = current_user
    end 
 
    def create
        @recipe = Recipe.create(recipe_params)
        @recipe.user_id = session[:user_id]
        @recipe.ingredient_id = Ingredient.find_or_create_by!(name: params[:recipe][:ingredient]).id
        # binding.pry
        if @recipe.valid?
            @recipe.save
            # binding.pry
            redirect_to recipe_path(id: current_user.id)
        else 
            render :new
        end 
    end
    

    def show
        # binding.pry
        @recipe = current_user.recipes
        @user = current_user.id
        # binding.pry
    end

    def edit
        @recipe = Recipe.find_by(id: params[:id])
        @user = current_user
        if !logged_in?
            redirect_to '/login'
        else 
            if current_user.id == @recipe.user_id
                render :edit
            else
                redirect_to '/'
            end 
        end 
    end 

    def update
        @recipe = Recipe.find_by(name: params[:recipe][:name])
        @recipe.update(recipe_params)
        @recipe.save
        redirect_to recipe_index_path(user_id: current_user.id)
    end 

    def destroy
        if current_user
            @recipe = Recipe.find_by(id: params[:id]).destroy
            redirect_to recipe_path(id: current_user.id)
        end 
    end
    
    private

    def recipe_params
        params.require(:recipe).permit(:name, :content)
    end
    
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def created
        #needs to use scope method .created from recipe class and redirect to
        #show utilizing this scope method
    end 

    def index
        @recipe = Recipe.all
    end 

    def new 
        @recipe = Recipe.new
    end 

    def create
        # user = User.create(user_params)
        # if user.valid?
        #     session[:user_id] = user.id
        #     redirect_to user
        # else 
        #     render :new
        # end 
    end
    

    def show

        # if session[:user_id]
        #     @user = User.find(params[:id])
        # else 
        #     redirect_to '/'
        # end 
    end

    def edit

    end 

    def update
        
    end 

    def destroy
        if current_user
            session.delete :user_id
            redirect_to '/'
        end 
    end
    
    private

    def user_params
        params.require(:recipe).permit(:name, :ingredients, :user_id))
    end
    
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipe/edit.html.erb
<%= form_for @recipe do |f| %>
    <%= f.label 'Name of Recipe' %>
    <%= f.text_field :name %></br>
    </br>
    <%= f.text_area :content %></br>
    </br>
    <%= f.submit %>
  
<% end %>


</br>
<button><%= link_to "Delete Recipe!", recipe_path(@recipe), :method => :delete %></button></br>  
</br>
<button><%= link_to "Create an Ingredient!", ingredients_path %></button></br>
</br>
<button><%= link_to "Logout", '/logout' %></button>
  

app/views/recipe/index.html.erb
<h1>All Recipes</h1>

<% Recipe.all.each do |recipe| %>
    <h5><%= recipe.name %> ~ <i><%= recipe.user.username %></i></h5>
    <i><%= recipe.content %></i></br>
<% end %></br>

<button><%= link_to "My Recipes", recipe_path(id: @user.id) %></button></br>
</br>
<button><%= link_to "Create a Recipe!", new_recipe_path(@user) %></button></br>
</br>
<button><%= link_to "Create an Ingredient!", ingredients_path %></button></br>
</br>
<button><%= link_to "Logout", '/logout' %></button></br>

app/views/recipe/new.html.erb
<p>SESSION ID = <%= session[:user_id] %></p>

<%= form_for @recipe, url: "/recipe", method: :post do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
        <h2>There were some errors:</h2>
        <ul>
            <% @recipe.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
  <% end %>
  <div class="field<%= ' field_with_errors' if @recipe.errors[:name].any? %>">
  <%= f.label 'Name of Recipe' %></br>
  <%= f.text_field :name %></br>
  </div>
  </br>
  <div class="field<%= ' field_with_errors' if @recipe.errors[:name].any? %>">
  <%= f.label 'Write out your recipe here' %></br>
  <%= f.text_area :content %></br>
  </div>
  </br>
  <div class="field<%= ' field_with_errors' if @recipe.errors[:name].any? %>">
  <i>Select one of your ingredients's to add this recipe to it</i></br>
  <%= f.collection_select :ingredient, Ingredient.all, :name, :name, {include_blank: 'Select an Ingredient'} %></br>
  </div>
  </br>
  <%= f.submit %>

<% end %>

</br>
<button><%= link_to "Create an Ingredient!", ingredients_path %></button></br>
</br>
<button><%= link_to "Logout", '/logout' %></button>

app/views/recipe/show.html.erb
<h1>Welcome to the Recipe Show!</h1>

<% if @recipe %>
  <% @recipe.each do |recipe| %>
    <h5><%= link_to recipe.name, edit_recipe_path(user_id: @user, id: recipe.id) %> ~ <%= current_user.username %></h5>
    <i><%= recipe.content %></i>
  <% end %>
<% else %>
  <p>No recipes to show</p>
  <p>Create your first recipe below</p>
<% end %>

</br>
<button><%= link_to "Create a Recipe!", new_recipe_path(@user) %></button></br>
</br>
<button><%= link_to "Create an Ingredient!", ingredients_path %></button></br>
</br>
<button><%= link_to "Logout", '/logout' %></button>